version: 2
updates:
  - package-ecosystem: npm
    directory: "/Lec-102 Soln  Quiz-17"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-104 Hosting Express App"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-105 Intro to ReactJs/shaurya_app"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-106 Components, Props and JSX in React /shaurya-project"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-107 Hooks & State in React/hooks-react"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-108 useEffect Hook/shaurya-useeffect"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-109 useRef React"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-110 Conditional Rendering &Rendering Lists "
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-85 Backend NodeJS & NPM"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-86 CommonJS VS EcmaScript"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-87 Working with Files FS & Path Modules"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-88 Intro to ExpressJS"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-89 Response Requests & Routers in Express "
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-90 Middleware in ExpressJS"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-92 EJS Template"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-93(Quiz - 15 Sort the Files Soln)"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-96 Mongoose  using with Express"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-98 Tailwind CSS"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: "/Lec-99 (Quiz - 16 Soln)"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
